version: '3.8'

services:
  instagram-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ig-live-monitor
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CHANNEL_ID=${DISCORD_CHANNEL_ID}
    volumes:
      # 掛載配置文件（只讀）
      - ./config.json:/app/config.json:ro
      - ./cookies.json:/app/cookies.json:ro
      # 可選：掛載日誌目錄
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # 資源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M